const nameMapping = {
    'MIEC_CSSE_课程笔记.md': 'MIEC CSSE 课程笔记',
    '9.13_Electrostatics.md': '9.13 静电学 Electrostatics',
    '12.6_Introduction_to_Telecoms.md': '12.6 电信介绍 Introduction to Telecoms',
    '9.24_Voltage,_Current_and_Resistance.md': '9.24 电压、电流和电阻 Voltage, Current and Resistance',
    '11.29_Other_Basic_Components.md': '11.29 其他基本组件 Other Basic Components',
    '10.4_Kirchhoff\'s_Law.md': '10.4 基尔霍夫定律 Kirchhoff\'s Law',
    '12.6_Signals_Noise.md': '12.6 信号噪声 Signals Noise',
    '9.13_Introduction_to_EE121FZ.md': '9.13 EE121FZ 介绍 Introduction to EE121FZ',
    '9.27_Voltage,_Current_and_Resistance.md': '9.27 电压、电流和电阻 Voltage, Current and Resistance',
    '12.xx_Modulation_Multiplexing.md': '12.xx 调制与多路复用 Modulation Multiplexing',
    '10.25_Maximum_Power_Transfer_Theorem.md': '10.25 最大功率传输定理 Maximum Power Transfer Theorem',
    '12.13_Analog_&_Digital_Signals.md': '12.13 模拟与数字信号 Analog & Digital Signals',
    '11.29_Generation_and_Distribution.md': '11.29 发电与配电 Generation and Distribution',
    '12.13_Channel_Capacity.md': '12.13 信道容量 Channel Capacity',
    '12.6_Signals_Radio_Propagation_-_DK.md': '12.6 信号无线电传播 DK Signals Radio Propagation - DK',
    '11.1_Basic_Circuit_Theory_1.md': '11.1 基本电路理论1 Basic Circuit Theory 1',
    '11.8_Basic_Circuit_Theory_2.md': '11.8 基本电路理论2 Basic Circuit Theory 2',
    '4._Boolean_Minimisation_Using_Karnaugh_Maps.md': '4. 使用卡诺图进行布尔最小化 Boolean Minimisation Using Karnaugh Maps',
    '6._Sequential_Logic_&_Flipflops.md': '6. 时序逻辑与触发器 Sequential Logic & Flipflops',
    '5._Implementation_Using_NAND_NOR_Gates.md': '5. 使用NAND和NOR门的实现 Implementation Using NAND NOR Gates',
    '7._Counters_&_Registers.md': '7. 计数器与寄存器 Counters & Registers',
    '2._Boolean_Logic_and_Basic_Gates.md': '2. 布尔逻辑和基本门 Boolean Logic and Basic Gates',
    '3._Boolean_Minimisation_Using_Boolean.md': '3. 使用布尔代数进行布尔最小化 Boolean Minimisation Using Boolean',
    '9._Programmable_Logic_Devices.md': '9. 可编程逻辑器件 Programmable Logic Devices',
    '1._Binary_Number_Representation.md': '1. 二进制数表示 Binary Number Representation',
    '8._Multi-Output_Networks_&_7-Segment_Displays.md': '8. 多输出网络与七段显示器 Multi-Output Networks & 7-Segment Displays',
    '关于_Java_的_Hello_world_解析.md': '关于 Java 的 Hello world 解析',
    '二维数组.md': '二维数组',
    '字符串.md': '字符串',
    '关键字与运算符.md': '关键字与运算符',
    '数据类型转换.md': '数据类型转换',
    '文件系统和_Cluster_等概念.md': '文件系统和 Cluster 等概念',
    '一维数组.md': '一维数组',
    'Java_随机数.md': 'Java 随机数',
    '计算机基础结构.md': '计算机基础结构',
    '文件.md': '文件',
    '数据输入（控制台）.md': '数据输入（控制台）',
    'IEEE_754.md': 'IEEE 754',
    '一点基本的网络知识.md': '一点基本的网络知识',
    '二进制的加减法和乘法.md': '二进制的加减法和乘法',
    'Java_变量基础知识.md': 'Java 变量基础知识',
    '异常处理.md': '异常处理',
    'Lecture_5&6__递归.md': 'Lecture 5&6 递归',
    'Lecture_8__有限状态机_Finite_State_Machine.md': 'Lecture 8 有限状态机 Finite State Machine',
    'Lecture_13__Inheritance.md': 'Lecture 13 继承 Inheritance',
    'Lecture_11__Advanced_Machine_Learning（不考）.md': 'Lecture 11 高级机器学习（不考） Advanced Machine Learning',
    'Lecture_2&3__Methods.md': 'Lecture 2&3 方法 Methods',
    'Lecture_1__intro_&_revision.md': 'Lecture 1 介绍与复习 intro & revision',
    'Lecture_10__排序和搜索算法.md': 'Lecture 10 排序和搜索算法',
    'Lecture_4__Regular_Expression.md': 'Lecture 4 正则表达式 Regular Expression',
    'Lecture_14__图灵机_Turing_Machine.md': 'Lecture 14 图灵机 Turing Machine',
    'Lecture_12__Classes_Objects.md': 'Lecture 12 类与对象 Classes Objects',
    'About.md': 'About',
    'slide_15__势_Cardinality（有限集）.md': 'slide 15 势 Cardinality（有限集）',
    'side_11__谓词逻辑模型和有效性.md': 'side 11 谓词逻辑模型和有效性',
    'slide_9__Classifying_relations_关系分类.md': 'slide 9 关系分类 Classifying relations',
    'slide_14__函数_Functions.md': 'slide 14 函数 Functions',
    'slide_8__Relations_关系.md': 'slide 8 关系 Relations',
    'slide_4：命题逻辑：有效的推理.md': 'slide 4 命题逻辑：有效的推理',
    'slide_13__量词的自然演绎.md': 'slide 13 量词的自然演绎',
    'slide_5__Expressiveness.md': 'slide 5 表达能力 Expressiveness',
    'slide_7__三段论推理_Syllogistic_Reasoning.md': 'slide 7 三段论推理 Syllogistic Reasoning',
    'slide_17__Transfinite_Cardinals_超限势.md': 'slide 17 超限势 Transfinite Cardinals',
    'slide_12__自然演绎（natural_deduction）.md': 'slide 12 自然演绎 natural deduction',
    'slide_3：命题逻辑.md': 'slide 3 命题逻辑',
    'slide_2：推理.md': 'slide 2 推理',
    'slide_6__集合论：定义集合.md': 'slide 6 集合论：定义集合',
    'slide_1：课程大纲.md': 'slide 1 课程大纲',
    'slide_10__谓词逻辑_Predicate_Logic.md': 'slide 10 谓词逻辑 Predicate Logic',
    'slide_16__势_Cardinality（无限集）.md': 'slide 16 势 Cardinality（无限集）',
    'T02._Programming_Revision.md': 'T02. 编程复习 Programming Revision',
    'T04._Arrays_and_Array_Algorithms.md': 'T04. 数组和数组算法 Arrays and Array Algorithms',
    'T07._Stacks_and_Queue.md': 'T07. 栈和队列 Stacks and Queue',
    'T09._Recursion.md': 'T09. 递归 Recursion',
    'T08._Linked_Lists.md': 'T08. 链表 Linked Lists',
    'T01._Introduction.md': 'T01. 介绍 Introduction',
    'T05._Big_O_Notation.md': 'T05. 大O表示法 Big O Notation',
    'Overview.md': 'Overview',
    'T03._Methods_and_Objects.md': 'T03. 方法和对象 Methods and Objects',
    'T06._Sorting_Algorithms.md': 'T06. 排序算法 Sorting Algorithms',
    'T10._Bit_Manipulation.md': 'T10. 位操作 Bit Manipulation',
    'T00._Course_Logistics.md': 'T00. 课程安排 Course Logistics',
    'Lecture_12._Mutation_Testing_变异测试.md': 'Lecture 12. 变异测试 Mutation Testing',
    'Lecture_14._Integration_Testing_集成测试.md': 'Lecture 14. 集成测试 Integration Testing',
    'Lecture_8._Branch_Coverage_分支覆盖.md': 'Lecture 8. 分支覆盖 Branch Coverage',
    'Lecture_4._Boundary_Value_Testing.md': 'Lecture 4. 边界值测试 Boundary Value Testing',
    'Lecture_0._Overview.md': 'Lecture 0. 概述 Overview',
    'Lecture_9._Conditon_Coverage_条件覆盖（没听懂）.md': 'Lecture 9. 条件覆盖 Conditon Coverage（没听懂）',
    'Lecture_3._Equivalence_Class_Testing.md': 'Lecture 3. 等价类测试 Equivalence Class Testing',
    'Lecture_7._Structural_Testing_-_Statement_Coverage_结构测试_-_语句覆盖.md': 'Lecture 7. 结构测试 - 语句覆盖 Structural Testing - Statement Coverage',
    'Lecture_6._Random_Testing_and_Error_Guessing.md': 'Lecture 6. 随机测试和错误猜测 Random Testing and Error Guessing',
    'Lecture_17._Testing_in_the_Software_Progress_软件过程中的测试.md': 'Lecture 17. 软件过程中的测试 Testing in the Software Progress',
    'Lecture_11._Dataflow_Coeverage_数据流覆盖.md': 'Lecture 11. 数据流覆盖 Dataflow Coeverage',
    'Lecture_16._Software_Test_Automation_软件测试自动化.md': 'Lecture 16. 软件测试自动化 Software Test Automation',
    'Lecture_1._Perspectives_and_Concepts.md': 'Lecture 1. 视角与概念 Perspectives and Concepts',
    'Lecture_5._Combinational_Testing.md': 'Lecture 5. 组合测试 Combinational Testing',
    'Lecture_13._Unit_Testing_-_Object_Oriented_Software_面向对象软件的单元测试.md': 'Lecture 13. 面向对象软件的单元测试 Unit Testing - Object Oriented Software',
    'Lecture_14._System_Testing_系统测试.md': 'Lecture 14. 系统测试 System Testing',
    'Lecture_2._Perspectives_and_Concepts.md': 'Lecture 2. 视角与概念 Perspectives and Concepts',
    'Lecture_10._Path_Coverage_路径覆盖（旷课了）.md': 'Lecture 10. 路径覆盖 Path Coverage（旷课了）',
    '安排.md': '安排',
    'Lecture_13._Deleting_and_Altering_Data_in_a_Database_删除和修改数据.md': 'Lecture 13. 删除和修改数据库中的数据 Deleting and Altering Data in a Database',
    'Lecture_18._Tables_as_Sets_in_SQL_表集合.md': 'Lecture 18. SQL中的表集合 Tables as Sets in SQL',
    'Lecture_14._Altering_Data_in_a_Database_TABLE_修改表.md': 'Lecture 14. 修改数据库表中的数据 Altering Data in a Database TABLE',
    'Lecture_20._Normalization_in_Databases_数据库标准化.md': 'Lecture 20. 数据库标准化 Normalization in Databases',
    'Lecture_6__More_Advanced_Pattern_Matching_高级模式匹配.md': 'Lecture 6. 更高级的模式匹配 More Advanced Pattern Matching',
    'Lecture_16._REFERENTIAL_INTEGRITY_in_JOINS,_CASCADING_DELETE_and_UPDATE_operations_级联删除、级联更新和_JOIN_的参照完整性.md': 'Lecture 16. 连接中的参照完整性、级联删除和更新操作 REFERENTIAL INTEGRITY in JOINS, CASCADING DELETE and UPDATE operations',
    'Lecture_11-12._Table_Aliases,_Working_with_Functions_in_SQL_and_PostgreSQL_表别名、函数.md': 'Lecture 11-12. 表别名、在SQL和PostgreSQL中使用函数 Table Aliases, Working with Functions in SQL and PostgreSQL',
    'Lecture_1.md': 'Lecture 1',
    'Lecture_5__Entity_Relationship_Modelling_实体关系模型.md': 'Lecture 5. 实体关系建模 Entity Relationship Modelling',
    'Lecture_10._Working_with_Primary_Keys_主键的使用.md': 'Lecture 10. 使用主键 Working with Primary Keys',
    'Lecture_19._SQL_Injection_Attack_and_Types_of_JOINS_in_SQL_注入攻击与_Join_的种类.md': 'Lecture 19. SQL注入攻击和SQL中连接的类型 SQL Injection Attack and Types of JOINS in SQL',
    'Lecture_0.md': 'Lecture 0',
    'Lecture_7._Creating_Tables_and_Inserting_Data_in_PostgreSQL_创建表和插入数据.md': 'Lecture 7. 在PostgreSQL中创建表和插入数据 Creating Tables and Inserting Data in PostgreSQL',
    'Lecture_3__Structured_Query_Language.md': 'Lecture 3. 结构化查询语言 Structured Query Language',
    'Lecture_4__More_Advanced_Usage_of_SQL.md': 'Lecture 4. SQL的更高级用法 More Advanced Usage of SQL',
    'Lecture_8._Working_with_Dates_and_Times_in_PostgreSQL_日期和时间的使用.md': 'Lecture 8. 在PostgreSQL中处理日期和时间 Working with Dates and Times in PostgreSQL',
    'Lecture_9._Data_Security,_DA,_DBA_数据安全与管理.md': 'Lecture 9. 数据安全、DA、DBA Data Security, DA, DBA',
    'Lecture_17._Relational_Algebra_and_Query_Planning_in_SQL_and_More_Referential_Integrity_关系代数、查询过程、参照完整性.md': 'Lecture 17. 关系代数和SQL中的查询计划及更多参照完整性 Relational Algebra and Query Planning in SQL and More Referential Integrity',
    'Lecture_2__Introduction_to_Data_Modelling_and_Database_Design.md': 'Lecture 2. 数据建模和数据库设计简介 Introduction to Data Modelling and Database Design',
    'Lecture_15._The_`HAVING`_Operator,_The_`LIMIT`_Operator,_Table_Constraints_运算符_`HAVING`、运算符_`LIMIT`、表限制.md': 'Lecture 15. HAVING运算符、LIMIT运算符、表约束 The `HAVING` Operator, The `LIMIT` Operator, Table Constraints',
    'About.md': 'About',
    'Lecture_6._Undecidability_不可判定性.md': 'Lecture 6. 不可判定性 Undecidability',
    'Lecture_8._Time_Complexity_时间复杂性.md': 'Lecture 8. 时间复杂性 Time Complexity',
    'Lecture_2._非确定型有限状态机（Nondeterministic_Finite_Automata）.md': 'Lecture 2. 非确定型有限状态机 Nondeterministic Finite Automata',
    'Lecture_10._NP_Complete_NP_完全.md': 'Lecture 10. NP完全 NP Complete',
    'Lecture_11._Introduction_to_Space_Complexity_空间复杂性引入.md': 'Lecture 11. 空间复杂性介绍 Introduction to Space Complexity',
    'Lecture_7._Reducibility_可归约性.md': 'Lecture 7. 可归约性 Reducibility',
    'Lecture_5._Decidability_可判定性.md': 'Lecture 5. 可判定性 Decidability',
    'L0._概括_Overview.md': 'L0. 概括 Overview',
    'Lecture_3._Context_Free_Languages_上下文无关语言.md': 'Lecture 3. 上下文无关语言 Context Free Languages',
    'Lecture_4._Turing_Machines_图灵机.md': 'Lecture 4. 图灵机 Turing Machines',
    'Lecture_9._The_Class_NP_NP_类.md': 'Lecture 9. NP类 The Class NP',
    'L1._数学初步与有限状态机_Math_Preliminaries_&_Finate_State_Automata.md': 'L1. 数学初步与有限状态机 Math Preliminaries & Finate State Automata',
    'Lecture_12._PSPACE-completeness_PSPACE_完全性.md': 'Lecture 12. PSPACE完全性 PSPACE-completeness',
    'Chapter_2_Part_2__一些硬件知识.md': 'Chapter 2 Part 2 一些硬件知识',
    'Chapter_4_Part_3.md': 'Chapter 4 Part 3',
    'Chapter_3_Part_2__触发器的应用以及时序逻辑电路设计.md': 'Chapter 3 Part 2 触发器的应用以及时序逻辑电路设计',
    'Chapter_3_Part_1__触发器_flip_flop.md': 'Chapter 3 Part 1 触发器 flip flop',
    'Chapter_5,_6,_7.md': 'Chapter 5, 6, 7',
    'Overview.md': 'Overview',
    'Chapter_4_Part_2.md': 'Chapter 4 Part 2',
    '阅读_CSAPP_关于算术运算的笔记.md': '阅读 CSAPP 关于算术运算的笔记',
    'Chapter_4_Part_1.md': 'Chapter 4 Part 1',
    'Chapter_2_Part_4__一大堆硬件电路（组合逻辑）.md': 'Chapter 2 Part 4 一大堆硬件电路（组合逻辑）',
    'Chapter_3_Part_3__算术运算.md': 'Chapter 3 Part 3 算术运算',
    'Chapter_1__Number_System_进制和数的表示.md': 'Chapter 1 进制和数的表示 Number System',
    'Chaper_2_Part_1__Boolean_Algebra_布尔代数.md': 'Chaper 2 Part 1 布尔代数 Boolean Algebra',
    'Chapter_2_Part_3__卡诺图.md': 'Chapter 2 Part 3 卡诺图',
    'About.md': 'About',
    'Lecture_7_结构设计.md': 'Lecture 7 结构设计',
    'Lecture_9_软件测试与调试.md': 'Lecture 9 软件测试与调试',
    'Lecture_2_软件过程.md': 'Lecture 2 软件过程',
    'Lecture_3_敏捷软件开发.md': 'Lecture 3 敏捷软件开发',
    'Lecture_8_系统设计.md': 'Lecture 8 系统设计',
    '概览.md': '概览',
    'Lecture_11._项目管理.md': 'Lecture 11. 项目管理',
    'Lecture_4_设计模式.md': 'Lecture 4 设计模式',
    'Lecture_1_引入.md': 'Lecture 1 引入',
    'Lecture_5_系统建模.md': 'Lecture 5 系统建模',
    'Lecture_10._UI_与_UX_设计.md': 'Lecture 10. UI 与 UX 设计',
    'Lecture_6_需求工程.md': 'Lecture 6 需求工程',
    'Lecture_2._md_Part2（颜色、图片、表格、列表）.md': 'Lecture 2. md Part2（颜色、图片、表格、列表）',
    'Chapter_8._CSS_Part3（显示样式、位置、浮动）.md': 'Chapter 8. CSS Part3（显示样式、位置、浮动）',
    'Chapter_11._JS_Part1（引用方式、显示信息、修改元素、语法类型）.md': 'Chapter 11. JS Part1（引用方式、显示信息、修改元素、语法类型）',
    'Chapter_4&5._md5_特性与编码规范.md': 'Chapter 4&5. md5 特性与编码规范',
    'Chapter_6._CSS_Part1（语法、背景、边框、留白）.md': 'Chapter 6. CSS Part1（语法、背景、边框、留白）',
    'Lecture_1._md_Part1（标签、CSS、格式化、引用）.md': 'Lecture 1. md Part1（标签、CSS、格式化、引用）',
    'Chapter_13._DOM.md': 'Chapter 13. DOM',
    'Lecture_3._md_Part3.md': 'Lecture 3. md Part3',
    'Chapter_7._CSS_Part2（留白、文本、字体、链接、列表、表格）.md': 'Chapter 7. CSS Part2（留白、文本、字体、链接、列表、表格）',
    'Chapter_14.md': 'Chapter 14',
    '概览.md': '概览',
    'Lecture_12._JS_对象.md': 'Lecture 12. JS 对象',
    'Chapter_10._CSS_Part5（属性选择器、动画、分页）.md': 'Chapter 10. CSS Part5（属性选择器、动画、分页）',
    'Chapter_9._CSS_Part4（对齐、选择器、伪类、导航条、下拉框）.md': 'Chapter 9. CSS Part4（对齐、选择器、伪类、导航条、下拉框）',
    'Lecture_8._Unix_管道与套接字（16_页）.md': 'Lecture 8. Unix 管道与套接字（16页）',
    'Lecture_19.20_内存管理二：虚拟内存等（46_页）.md': 'Lecture 19.20 内存管理二：虚拟内存等（46页）',
    'Lecture_10._线程（25_页）.md': 'Lecture 10. 线程（25页）',
    'Lecture_9._Unix_消息队列与远程过程调用（22_页）.md': 'Lecture 9. Unix 消息队列与远程过程调用（22页）',
    'Lecture_18._引入内存管理（28_页）.md': 'Lecture 18. 引入内存管理（28页）',
    'Lecture_11._互斥锁问题（22_页）.md': 'Lecture 11. 互斥锁问题（22页）',
    'Lecture._1_OS_概述（25_页）.md': 'Lecture. 1 OS 概述（25页）',
    'Lecture_14_生产者-消费者问题（有节缓冲问题）（21_页）.md': 'Lecture 14 生产者-消费者问题（有节缓冲问题）（21页）',
    'Lecture_2._进程管理（26_页）.md': 'Lecture 2. 进程管理（26页）',
    'Lecture_4._进程调度_2：抢占式调度（25_页）.md': 'Lecture 4. 进程调度2：抢占式调度（25页）',
    '概览.md': '概览',
    'Lecture_6._磁盘操作与磁盘调度（21_页）.md': 'Lecture 6. 磁盘操作与磁盘调度（21页）',
    'Lecture_15.16_哲学家就餐以及读者作者问题（42_页）.md': 'Lecture 15.16 哲学家就餐以及读者作者问题（42页）',
    'Lecture_17._死锁（31_页）.md': 'Lecture 17. 死锁（31页）',
    'Lecture_3._进程调度_1：非抢占式调度（24_页）.md': 'Lecture 3. 进程调度1：非抢占式调度（24页）',
    'Lecture_21.22.23_文件系统（71_页）.md': 'Lecture 21.22.23 文件系统（71页）',
    'Lecture_12._解决临界区问题的算法（25_页）.md': 'Lecture 12. 解决临界区问题的算法（25页）',
    'Lecture_5._进程调度_3_关于进程调度的数学建模（26_页）.md': 'Lecture 5. 进程调度3：关于进程调度的数学建模（26页）',
    'Lecture_7._UNIX_的进程管理与进程间通信（30_页）.md': 'Lecture 7. UNIX 的进程管理与进程间通信（30页）',
    'Lecture_13._信号量（23_页）.md': 'Lecture 13. 信号量（23页）',
    'Lecture_10._密码学.md': 'Lecture 10. 密码学',
    'Lecture_2._Divide_and_Conquer_分治.md': 'Lecture 2. 分治 Divide and Conquer',
    'Lecture_1._Foundations_基础知识.md': 'Lecture 1. 基础知识 Foundations',
    'Lecture_4._树.md': 'Lecture 4. 树',
    'Lecture_9._回溯算法.md': 'Lecture 9. 回溯算法',
    'Lecture_3._Hash_Tables_哈希表.md': 'Lecture 3. 哈希表 Hash Tables',
    'Lecture_6._动态规划.md': 'Lecture 6. 动态规划',
    '概览.md': '概览',
    'Lecture_8._暴力.md': 'Lecture 8. 暴力',
    'Lecture_5._图.md': 'Lecture 5. 图',
    'Lecture_7._贪心算法.md': 'Lecture 7. 贪心算法',
    'Lecture_11._P、NP、NP_完全.md': 'Lecture 11. P、NP、NP 完全',
    'Lecture_6._汇编语言_Part5：浮点与_8087.md': 'Lecture 6. 汇编语言 Part5：浮点与 8087',
    'Lecture_13.A_硬盘、CD-ROM.md': 'Lecture 13.A 硬盘、CD-ROM',
    'Lecture_9._IO_与中断.md': 'Lecture 9. IO 与中断',
    'Lecture_2._汇编语言_Part1：寄存器与基础汇编结构知识.md': 'Lecture 2. 汇编语言 Part1：寄存器与基础汇编结构知识',
    'Lecture_3._汇编语言_Part2：寻址模式与指令格式.md': 'Lecture 3. 汇编语言 Part2：寻址模式与指令格式',
    'Lecture_15._总线.md': 'Lecture 15. 总线',
    'Lecture_7._半导体与_PN_结二极管.md': 'Lecture 7. 半导体与 PN 结二极管',
    'Lecture_4._汇编语言_Part3：算术、逻辑、位、转移指令.md': 'Lecture 4. 汇编语言 Part3：算术、逻辑、位、转移指令',
    'Lecture_14._RISC_VS_CISC、现代计算机技术.md': 'Lecture 14. RISC VS CISC、现代计算机技术',
    'Lecture_10._关于中断与_TSR_的汇编实现.md': 'Lecture 10. 关于中断与 TSR 的汇编实现',
    '概览.md': '概览',
    'Lecture_12._内存管理与缓存策略.md': 'Lecture 12. 内存管理与缓存策略',
    'Lecture_8._晶体管和_FET.md': 'Lecture 8. 晶体管和 FET',
    'Lecture_11._内存与动态、静态_RAM.md': 'Lecture 11. 内存与动态、静态 RAM',
    'Lecture_5._汇编语言_Part4：整数，实数，字符串.md': 'Lecture 5. 汇编语言 Part4：整数，实数，字符串',
    'Lecture_16._闪存与_FGPA.md': 'Lecture 16. 闪存与 FGPA',
    'Lecture_13.B_硬件保护.md': 'Lecture 13.B 硬件保护',
    'Lecture_1._CPU.md': 'Lecture 1. CPU',
    'Chapter_7_关于均值的推断.md': 'Chapter 7 关于均值的推断',
    'Chapter_8_比较两个对象.md': 'Chapter 8 比较两个对象',
    'Chapter_5_概率密度_Probability_Density.md': 'Chapter 5 概率密度 Probability Density',
    'Chapter_2_描述数据的方法.md': 'Chapter 2 描述数据的方法',
    'Chapter_3_概率.md': 'Chapter 3 概率',
    '概览.md': '概览',
    'Chapter_1.md': 'Chapter 1',
    'Chapter_9_方差.md': 'Chapter 9 方差',
    'Chapter_4_概率分布.md': 'Chapter 4 概率分布',
    'Chapter_6_样本分布.md': 'Chapter 6 样本分布',
    'Chapter_4&5._HTML5_特性与编码规范.md': 'Chapter 4&5. HTML5 特性与编码规范',
    'Lecture_1._HTML_Part1（标签、CSS、格式化、引用）.md': 'Lecture 1. HTML Part1（标签、CSS、格式化、引用）',
    'Lecture_2._HTML_Part2（颜色、图片、表格、列表）.md': 'Lecture 2. HTML Part2（颜色、图片、表格、列表）',
    'Lecture_3._HTML_Part3.md': 'Lecture 3. HTML Part3',
};